name: pass_rate
description: "PassRate - Pilot Assessment App"
publish_to: 'none'

version: 1.2.3+8

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.7.0
  firebase_app_check: ^0.4.3
  cloud_firestore: ^6.3.0
  get: ^4.7.2
  intl: ^0.20.2
  device_info_plus: ^11.4.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animation/
  fonts:
    - family: satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700
