// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAACELQ70qc3CbCAQm3XMASRZDR5f54j7A',
    appId: '1:5132550360:web:ad83d58796f85980c1d7ad',
    messagingSenderId: '5132550360',
    projectId: 'passrate-4360d',
    authDomain: 'passrate-4360d.firebaseapp.com',
    storageBucket: 'passrate-4360d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUf-E1Z9GMzkeDYhu68HRXpeEhDV9alg',
    appId: '1:5132550360:android:5f2d965b2d9eeec5c1d7ad',
    messagingSenderId: '5132550360',
    projectId: 'passrate-4360d',
    storageBucket: 'passrate-4360d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD1MWwRPR5qyyENp3i8vryBIthDbVjbGY',
    appId: '1:5132550360:ios:2c5ec733049aaeafc1d7ad',
    messagingSenderId: '5132550360',
    projectId: 'passrate-4360d',
    storageBucket: 'passrate-4360d.firebasestorage.app',
    iosBundleId: 'com.example.passRate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD1MWwRPR5qyyENp3i8vryBIthDbVjbGY',
    appId: '1:5132550360:ios:2c5ec733049aaeafc1d7ad',
    messagingSenderId: '5132550360',
    projectId: 'passrate-4360d',
    storageBucket: 'passrate-4360d.firebasestorage.app',
    iosBundleId: 'com.example.passRate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAACELQ70qc3CbCAQm3XMASRZDR5f54j7A',
    appId: '1:5132550360:web:c4f7ac5aab40990ec1d7ad',
    messagingSenderId: '5132550360',
    projectId: 'passrate-4360d',
    authDomain: 'passrate-4360d.firebaseapp.com',
    storageBucket: 'passrate-4360d.firebasestorage.app',
  );
}
